// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjprnsvwezvlckjuihkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqcHJuc3Z3ZXp2bGNranVpaGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjc2MDMsImV4cCI6MjA2NjYwMzYwM30.U2PpCaiClDMggDZsIusBjBWOznVx92TSMLVrK2F8QCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);